/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import ayuda.AyudaBajaCliente;
import controlDental.Cliente;
import controlar.BaseDeDatos;
import controlar.Imprimir;
import controlar.TransaccionCliente;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mourad Daoudi
 */
public class BajaCliente extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    /**
     * Creates new form BajaCliente1
     */
    public BajaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setTitle("Baja y consulta de Cliente");

        jLabel1.setText("Buscar:");

        jLabel2.setText("Buscar Por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "Nombre", "Apellidos", "Fecha nacimiento", "Sexo", "Código Postal" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ordenar por:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "Nombre", "Apellidos", "Fecha nacimiento", "Sexo", "Código Postal" }));

        jButton7.setText("Ayuda");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Sexo", "Fecha Nacimiento", "Dirección", "Localidad", "C.P", "Alergias", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 309));

        jLabel4.setText("Rellene todos los campos para eliminar un cliente, o ponga el DNI y pulse Rellenar Campos.");

        jLabel5.setText("DNI:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Apellidos:");

        jLabel8.setText("Sexo:");

        jLabel9.setText("Fecha Nacimiento:");

        jLabel10.setText("Dirección:");

        jLabel11.setText("Localidad:");

        jLabel12.setText("Código Postal:");

        jLabel13.setText("Alergias:");

        jLabel14.setText("Descripción:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        jButton4.setText("Eliminar Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Formato fecha: dd/mm/aaaa");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("El dni se debe introducir sin letra");

        jButton5.setText("Rellenar Campos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(31, 31, 31))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jTextField6)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Imprimir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(71, 71, 71))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
//Boton buscar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList <Cliente> clientes = new ArrayList();
        BaseDeDatos.conectar();
        String campo = jComboBox1.getSelectedItem().toString();
        String clave = jTextField1.getText();

        modelo = (DefaultTableModel) jTable1.getModel();

        int numrows = modelo.getRowCount();
        for (int i = numrows - 1; i  >= 0; i--) {
            modelo.removeRow(i);
        }

        String ordenado = jComboBox2.getSelectedItem().toString();
        if (ordenado.compareTo("DNI")==0){
            ordenado= "DNI";
            
        }else if (ordenado.compareTo("Nombre")==0){
            ordenado="NOMBRE";
                    
        }else if(ordenado.compareTo("Apellidos")==0){

             ordenado="APELLIDOS";
        }else if(ordenado.compareTo("Fecha nacimiento")==0){
            ordenado="FECHA_NACIMIENTO";

        }else if(ordenado.compareTo("Sexo")==0){
            ordenado="SEXO";
        }else if(ordenado.compareTo("Código Postal")==0){
             ordenado="CP";
        }

        if (campo.compareTo("DNI")==0){

            int claveNumerica = Integer.parseInt(clave);
            
            clientes=TransaccionCliente.buscarClientePorDni(claveNumerica, ordenado);

            for (int i=0; i < clientes.size(); i++){

                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);

            }

        }else if(campo.compareTo("Nombre")==0){

            clientes=TransaccionCliente.buscarClientePorNombre(clave, ordenado);
            for (int i=0; i < clientes.size(); i++){
                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);
            }

        }else if(campo.compareTo("Fecha nacimiento")==0){

            clientes=TransaccionCliente.buscarClientePorFechaNacimiento(clave,ordenado);
            for (int i=0; i < clientes.size(); i++){
                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);
            }

        }else if(campo.compareTo("Sexo")==0){

            clientes=TransaccionCliente.buscarClientePorSexo(clave, ordenado);
            for (int i=0; i < clientes.size(); i++){
                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);
            }

        }else if(campo.compareTo("Apellidos")==0){

            clientes=TransaccionCliente.buscarClientePorApellidos(clave, ordenado);
            for (int i=0; i < clientes.size(); i++){
                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);
            }

        }else if(campo.compareTo("Código Postal")==0){
            
            int claveNumerica = Integer.parseInt(clave);

            clientes=TransaccionCliente.buscarClientePorCodigoPostal(claveNumerica, ordenado);
            for (int i=0; i < clientes.size(); i++){
                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed
//Boton rellenar campos
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ArrayList <Cliente> clientes = new ArrayList();
        int dni;
        try{
         dni = Integer.parseInt(jTextField2.getText());
        }catch(NumberFormatException e){
            String msg = "Introduce un DNI válido(8 digitos numéricos).";
            JOptionPane.showMessageDialog(null, msg, "Error", 0);
            dni=0;
        }
        BaseDeDatos.conectar();
        
        clientes=TransaccionCliente.buscarClientePorDni(dni, "DNI");
        jTextField3.setText(clientes.get(0).getNombre());
        jTextField4.setText(clientes.get(0).getApellidos());
        if (clientes.get(0).getSexo().compareTo("H")==0) {
            jComboBox3.setSelectedItem("Hombre");
        }else {
            jComboBox3.setSelectedItem("Mujer");
        }
        jTextField5.setText(clientes.get(0).getFechaNacimiento());
        jTextField6.setText(clientes.get(0).getDireccion());
        jTextField7.setText(clientes.get(0).getLocalidad());
        int codigo = clientes.get(0).getCodigo_postal();
        jTextField8.setText(String.valueOf(codigo));
        jTextField9.setText(clientes.get(0).getAlergias());
        jTextField10.setText(clientes.get(0).getDescripcion());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BaseDeDatos.conectar();
        TransaccionCliente.borrarCliente(Integer.parseInt(jTextField2.getText()));
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
           String msg = "Cliente eliminado correctamente.";
            JOptionPane.showMessageDialog(null, msg, "Confirmación", 1);
    }//GEN-LAST:event_jButton4ActionPerformed
    //Botón de Listar
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList <Cliente> clientes = new ArrayList();
        BaseDeDatos.conectar();
        String ordenado = jComboBox2.getSelectedItem().toString();
        if (ordenado.compareTo("DNI")==0){
            ordenado= "DNI";
            
        }else if (ordenado.compareTo("Nombre")==0){
            ordenado="NOMBRE";
                    
        }else if(ordenado.compareTo("Apellidos")==0){

             ordenado="APELLIDOS";
        }else if(ordenado.compareTo("Fecha nacimiento")==0){
            ordenado="FECHA_NACIMIENTO";

        }else if(ordenado.compareTo("Sexo")==0){
            ordenado="SEXO";
        }else if(ordenado.compareTo("Código Postal")==0){
             ordenado="CP";
        }
        clientes=TransaccionCliente.listarCliente(ordenado);
        modelo = (DefaultTableModel) jTable1.getModel();
        
        
        if (ordenado.compareTo("DNI")==0){
            ordenado= "DNI";
            
        }else if (ordenado.compareTo("Nombre")==0){
            ordenado="NOMBRE";
                    
        }else if(ordenado.compareTo("Apellidos")==0){

             ordenado="APELLIDOS";
        }else if(ordenado.compareTo("Fecha nacimiento")==0){
            ordenado="FECHA_NACIMIENTO";

        }else if(ordenado.compareTo("Sexo")==0){
            ordenado="SEXO";
        }else if(ordenado.compareTo("Código Postal")==0){
             ordenado="CP";
        }

        int numrows = modelo.getRowCount();
        for (int i = numrows - 1; i  >= 0; i--) {
            modelo.removeRow(i);
        }
        for (int i=0; i < clientes.size(); i++){

                modelo.addRow(new Object[]{});
                jTable1.setValueAt(clientes.get(i).getDni(), i, 0);
                jTable1.setValueAt(clientes.get(i).getNombre(), i, 1);
                jTable1.setValueAt(clientes.get(i).getApellidos(), i, 2);
                jTable1.setValueAt(clientes.get(i).getSexo(), i, 3);
                jTable1.setValueAt(clientes.get(i).getFechaNacimiento(), i, 4);
                jTable1.setValueAt(clientes.get(i).getDireccion(), i, 5);
                jTable1.setValueAt(clientes.get(i).getLocalidad(), i, 6);
                jTable1.setValueAt(clientes.get(i).getCodigo_postal(), i, 7);
                jTable1.setValueAt(clientes.get(i).getAlergias(), i, 8);
                jTable1.setValueAt(clientes.get(i).getDescripcion(), i, 9);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AyudaBajaCliente ayudaBajaCliente = new AyudaBajaCliente();
        ayudaBajaCliente.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
