/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import ayuda.AyudaGeneral;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mourad Daoudi
 */
public class menuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modo Administrador Gestión Dental");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_diente.png")));
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 204));

        jMenu4.setText("Archivo");

        jMenuItem8.setText("Copia de Seguridad");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Cliente");

        jMenuItem1.setText("Alta Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Baja/Consulta Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Modificar Cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Usuarios");

        jMenuItem7.setText("Alta Usuario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem10.setText("Baja Usuario");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem9.setText("Modificar Usuario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setText("Ayuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Acerca de");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.jDesktopPane1.removeAll();
       this.jDesktopPane1.repaint();
        
       AltaUsuario usuario = null;
        try {
            usuario = new  AltaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(menuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jDesktopPane1.add(usuario);
        try {
            usuario.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        usuario.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.jDesktopPane1.removeAll();
       this.jDesktopPane1.repaint();
        
       ModificarUsuario modificarUsuario = null;
        try {
            modificarUsuario = new  ModificarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(menuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jDesktopPane1.add(modificarUsuario);
        try {
            modificarUsuario.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        modificarUsuario.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
      this.jDesktopPane1.removeAll();
       this.jDesktopPane1.repaint();
        
       BajaUsuario bajaUsuario = null;
        try {
            bajaUsuario = new  BajaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(menuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jDesktopPane1.add(bajaUsuario);
        try {
            bajaUsuario.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        bajaUsuario.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.jDesktopPane1.removeAll();
       this.jDesktopPane1.repaint();
        
        AltaCliente altaCliente = new AltaCliente();
        this.jDesktopPane1.add(altaCliente);
        try {
            altaCliente.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        altaCliente.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.jDesktopPane1.removeAll();
       this.jDesktopPane1.repaint();
        
        BajaCliente bajaCliente = new BajaCliente();
        this.jDesktopPane1.add(bajaCliente);
        try {
            bajaCliente.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        bajaCliente.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       this.jDesktopPane1.removeAll();
       this.jDesktopPane1.repaint();
        
        ModificarCliente modificarCliente = new ModificarCliente();
        this.jDesktopPane1.add(modificarCliente);
        try {
            modificarCliente.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        modificarCliente.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AcercaDe acerca =new AcercaDe();
        this.jDesktopPane1.add(acerca);
        acerca.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.repaint();
        CopiaSeguridad copias = new CopiaSeguridad();
        this.jDesktopPane1.add(copias);
        
        copias.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AyudaGeneral ayudaGeneral = new AyudaGeneral();
        ayudaGeneral.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
